data_path: "./dataset/knee-osteoarthritis"
checkpoint_path: "./checkpoints"

label_map:
  1: 1
  2: 1
  3: 2
  4: 2
label_map_legend:
  0: "Healthy"
  1: "Medium"
  2: "Severe"
num_of_samples: [ 173, 500 ]
img_size: [ 244, 244 ]
shuffle: True
augment: False

batch_size: 128
units: 128
dropout: 0.0
trainable_model: False
learning_rate: 1e-3
activation: "relu"
optimizer: "Adam"

seed: 42

